# Numpy

In [1]:
import numpy as np

In [2]:
# !pip install numpy

In [3]:
np.array(11)

array(11)

In [14]:
a = np.array([5,5])

In [15]:
a

array([5, 5])

In [16]:
np.array([102,20,30])

array([102,  20,  30])

In [18]:
np.array('Python')

array('Python', dtype='<U6')

In [19]:
np.array({1:100, 2:200})

array({1: 100, 2: 200}, dtype=object)

In [20]:
arr = np.array([10,20,30,40,50])
print(arr.size)
print(arr.shape)
print(arr.dtype)

5
(5,)
int32


In [ ]:
# Array is a collection of homogeneous


In [21]:
arr = np.array([10,20,30,40,50, 1.20])
print(arr, arr.dtype)

[10.  20.  30.  40.  50.   1.2] float64


In [22]:
int -> float -> complex -> string

SyntaxError: invalid syntax (<ipython-input-22-7c39344a9818>, line 1)

In [23]:
arr = np.array([10,20,30,40,50, 1.20, 'a'])
print(arr, arr.dtype)

['10' '20' '30' '40' '50' '1.2' 'a'] <U32


In [18]:
arr2 = np.array(((1,2),(3,4)))
print(arr2)
print(arr2.size)
print(arr2.shape)

[[1 2]
 [3 4]]
4
(2, 2)


In [16]:
# arange(start, stop ,step) - returns an array

# np.arange(10, 20, 2)

# np.arange(10, 20, 0.5)

array([10. , 10.5, 11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. ,
       15.5, 16. , 16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5])

In [26]:
# linspace(start, stop, np of elements) - stop is inclusive

c = np.linspace(10, -10, 20, dtype = int)
c.size


20

In [32]:
np.zeros((5,))
np.zeros((5,6), dtype = float)

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [33]:
d = np.ones((5,7) ,  dtype= float)
d

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [26]:
np.zeros_like([[1,2,3],[4,5,6],[7,8,9]])

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
[[1,2,3],
 [4,5,6],
 [7,8,9]]

In [28]:
# np.ones((5,))
# np.ones((5,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [30]:
np.ones_like([[10,22,34], [4,5,6]])

array([[1, 1, 1],
       [1, 1, 1]])

In [31]:
np.empty((9,7))

array([[-3.10503618e+231, -3.10503618e+231,  2.27362711e-314,
         2.27364593e-314,  2.27364594e-314,  5.43472210e-323,
         0.00000000e+000],
       [ 3.95252517e-323,  2.12199579e-314,  2.25632071e-314,
         0.00000000e+000,  6.95081854e-310,  0.00000000e+000,
         0.00000000e+000],
       [ 2.14027814e+161,  0.00000000e+000,  2.12199579e-314,
         3.97050920e+246,  8.19090375e-312,  9.84581941e-072,
         2.57543843e-056],
       [ 2.46998323e-056,  1.81728840e+185,  3.98450697e+252,
         1.02941932e-071,  6.97665885e-076,  4.86685744e-086,
         3.35860038e-143],
       [ 4.82337433e+228,  6.14415221e-144,  3.11352423e+179,
         2.25234621e-308,  6.95081859e-310,  9.58487353e-322,
         0.00000000e+000],
       [ 0.00000000e+000,  1.05889064e+200,  5.02034658e+175,
         2.00538631e-052,  2.57444466e-056,  2.46696841e+184,
         1.17794420e-047],
       [ 1.47763641e+248,  1.16096346e-028,  7.69165785e+218,
         1.35617292e+248,  3.366

In [32]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [34]:
np.arange(1, 10000)

array([   1,    2,    3, ..., 9997, 9998, 9999])

In [35]:
import sys
np.set_printoptions(threshold = sys.maxsize)

In [36]:
np.arange(1, 10000)

array([   1,    2,    3,    4,    5,    6,    7,    8,    9,   10,   11,
         12,   13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
         23,   24,   25,   26,   27,   28,   29,   30,   31,   32,   33,
         34,   35,   36,   37,   38,   39,   40,   41,   42,   43,   44,
         45,   46,   47,   48,   49,   50,   51,   52,   53,   54,   55,
         56,   57,   58,   59,   60,   61,   62,   63,   64,   65,   66,
         67,   68,   69,   70,   71,   72,   73,   74,   75,   76,   77,
         78,   79,   80,   81,   82,   83,   84,   85,   86,   87,   88,
         89,   90,   91,   92,   93,   94,   95,   96,   97,   98,   99,
        100,  101,  102,  103,  104,  105,  106,  107,  108,  109,  110,
        111,  112,  113,  114,  115,  116,  117,  118,  119,  120,  121,
        122,  123,  124,  125,  126,  127,  128,  129,  130,  131,  132,
        133,  134,  135,  136,  137,  138,  139,  140,  141,  142,  143,
        144,  145,  146,  147,  148,  149,  150,  1

In [46]:
# Changing the shape of an array

arr = np.arange(1, 10001)
print(arr.shape)
arr2 = arr.reshape(500, 20)
print(arr2)



(10000,)
[[    1     2     3     4     5     6     7     8     9    10    11    12
     13    14    15    16    17    18    19    20]
 [   21    22    23    24    25    26    27    28    29    30    31    32
     33    34    35    36    37    38    39    40]
 [   41    42    43    44    45    46    47    48    49    50    51    52
     53    54    55    56    57    58    59    60]
 [   61    62    63    64    65    66    67    68    69    70    71    72
     73    74    75    76    77    78    79    80]
 [   81    82    83    84    85    86    87    88    89    90    91    92
     93    94    95    96    97    98    99   100]
 [  101   102   103   104   105   106   107   108   109   110   111   112
    113   114   115   116   117   118   119   120]
 [  121   122   123   124   125   126   127   128   129   130   131   132
    133   134   135   136   137   138   139   140]
 [  141   142   143   144   145   146   147   148   149   150   151   152
    153   154   155   156   157   158   15

In [40]:
arr1 = np.arange(1, 501)
arr2 = arr1.reshape(5, 10, 10)
# arr3 = arr2.reshape(500,)
#print(arr2)
print(arr1)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108
 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126
 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144
 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162
 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180
 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198
 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216
 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234
 235 236 237 238 239 240 241 242 243 244 245 246 24

In [42]:
arr1 = np.arange(1, 399)
arr1.shape = 20, 20
print(arr1)

ValueError: cannot reshape array of size 398 into shape (20,20)

In [57]:
arr1 = np.array([['US', 'UK', 'IND', 'BAN'],
                 ['PAK', 'AFG', 'CHN', 'RUS'],
                 ['NPL', 'BHT', 'MYN', 'INDO']])
arr1.T     # rows to columns and columns to rows

array([['US', 'PAK', 'NPL'],
       ['UK', 'AFG', 'BHT'],
       ['IND', 'CHN', 'MYN'],
       ['BAN', 'RUS', 'INDO']], dtype='<U4')

In [63]:
arr1 = np.array([['US', 'UK', 'IND', 'BAN'],
                 ['PAK', 'AFG', 'CHN', 'RUS'],
                 ['NPL', 'BHT', 'MYN', 'INDO'],
                 ['BRZ', 'SA', 'MEX', 'CAN']])
arr1.reshape(8,-10)

array([['US', 'UK'],
       ['IND', 'BAN'],
       ['PAK', 'AFG'],
       ['CHN', 'RUS'],
       ['NPL', 'BHT'],
       ['MYN', 'INDO'],
       ['BRZ', 'SA'],
       ['MEX', 'CAN']], dtype='<U4')

In [60]:
arr1.reshape(2,-1)

array([['US', 'UK', 'IND', 'BAN', 'PAK', 'AFG', 'CHN', 'RUS'],
       ['NPL', 'BHT', 'MYN', 'INDO', 'BRZ', 'SA', 'MEX', 'CAN']],
      dtype='<U4')

In [61]:
arr1.reshape(-1,4)

array([['US', 'UK', 'IND', 'BAN'],
       ['PAK', 'AFG', 'CHN', 'RUS'],
       ['NPL', 'BHT', 'MYN', 'INDO'],
       ['BRZ', 'SA', 'MEX', 'CAN']], dtype='<U4')

In [62]:
arr1.reshape(-1,3)

ValueError: cannot reshape array of size 16 into shape (3)

In [64]:
arr1.shape = 4,-1
arr1

array([['US', 'UK', 'IND', 'BAN'],
       ['PAK', 'AFG', 'CHN', 'RUS'],
       ['NPL', 'BHT', 'MYN', 'INDO'],
       ['BRZ', 'SA', 'MEX', 'CAN']], dtype='<U4')

In [76]:
# Basic Operation on an array
arr1 = np.array([11, 22, 33, 44, 55])
arr2 = np.array([10, 20, 30, 40, 50])
# print(arr1 + arr2)
# print(arr1 - arr2)
# print(arr1 / arr2)
# print(arr1 * arr2)

print(arr1 > 30)




[False False  True  True  True]


In [79]:
# Scalar product
print(arr1 * 2)
print(arr1 * arr2)


# Vector product - .dot
arr1.dot(arr2)


[ 22  44  66  88 110]
[ 110  440  990 1760 2750]


6050

In [81]:
arr1 = np.array([[10,20,],
                [30,40]])
arr2 = np.array([[11, 22],
                 [33, 44]])

print(arr1.dot(arr2))

[[ 770 1100]
 [1650 2420]]


In [85]:
# Aggregate

arr1 = np.array([11, 110, 20, 2,2000, 30, 334, 56, 76])
print(arr1.sum())
print(arr1.max())
print(arr1.min())

2639
2000
2


In [86]:
arr2 = np.arange(25, 55).reshape(5, 6)
arr2

array([[25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54]])

In [87]:
print(arr2.sum())
print(arr2.max())
print(arr2.min())

1185
54
25


In [91]:
print(arr2.sum(axis = 0))
print(arr2.sum(axis = 1))

[185 190 195 200 205 210]
[165 201 237 273 309]


In [90]:
sum([25, 31, 37, 43, 49])

185

In [92]:
arr2.min(axis = 1)

array([25, 31, 37, 43, 49])

In [93]:
arr2.max(axis = 1)

array([30, 36, 42, 48, 54])

In [112]:
arr2 = np.arange(25, 55).reshape(5, 6)
arr2

array([[25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54]])

In [114]:
arr2[::2, 1:4:2]

array([[26, 28],
       [38, 40],
       [50, 52]])

In [102]:
arr1 = np.array([11, 110, 20, 2,2000, 30, 334, 56, 76])
# print(arr1[0])
# print(arr1[-1])
# print(arr1[2:5])
# print(arr1[2:5:2])

print(arr1[::-1])

[  76   56  334   30 2000    2   20  110   11]


In [107]:
# print(arr2[2][2])
# print(arr2[2,2])

print(arr2[2:, 3:])


[[40 41 42]
 [46 47 48]
 [52 53 54]]


In [116]:
arr2[3,4] = 444
print(arr2)

[[ 25  26  27  28  29  30]
 [ 31  32  33  34  35  36]
 [ 37  38  39  40  41  42]
 [ 43  44  45  46 444  48]
 [ 49  50  51  52  53  54]]


In [119]:
lst1=list(range(10))
list_1=list(filter(lambda x:x%2==0,lst1))
list_2= [x for x in lst1 if x%2 == 0]
print(list_1)
print(list_2)

[0, 2, 4, 6, 8]
[0, 2, 4, 6, 8]
